name: "Build application"
on: [push]
jobs:
    build-linux:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                channel: 'stable'
                flutter-version: 3.24.4

            - name: Install dependencies
              run: |
                echo flet >> requirements.txt
                echo markdownify >> requirements.txt
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: Patch for Linux build
              run: |
                flutter doctor
                sudo apt-get update -y
                sudo apt-get install -y ninja-build libgtk-3-dev
                flutter doctor

            - name: Flet build linux
              run: |
                flutter config --no-analytics
                flet build linux --verbose --no-rich-output --module-name gui

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: linux-build-artifact
                path: build/linux
                if-no-files-found: warn
                overwrite: false

    build-windows:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                channel: 'stable'
                flutter-version: 3.24.4

            - name: Install dependencies
              run: |
                echo flet >> requirements.txt
                echo markdownify >> requirements.txt
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Flet build windows
              run: |
                flutter config --no-analytics
                flet build windows --verbose --no-rich-output --module-name gui

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: windows-build-artifact
                path: build/windows
                if-no-files-found: warn
                overwrite: false